# Generated by Django 4.2.20 on 2025-04-21 15:40

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('file', models.FileField(upload_to='resumes/', validators=[blog.models.file_size_validator])),
            ],
        ),
    ]
